project:
  group: laplacian-arch
  name: service-api.schema-plugin
  type: schema-plugin
  namespace: laplacian.arch.service.api
  version: '1.0.0'
  description: |
    A schema for service-api architecture model.
  plugins:
  - group: laplacian-arch
    name: datasource.schema-plugin
    version: '1.0.0'
  models:
  - group: laplacian-arch
    name: datasource.schema-model
    version: '1.0.0'
  - group: laplacian-arch
    name: service-api.schema-model
    version: '1.0.0'
