project:
  group: laplacian
  name: projects
  type: project-group
  version: "1.0.0"
  description:
    en: |
      The core modules for the Laplacian generator.
  module_repositories:
    local:
      ../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  model_files:
  - dest/
