project:
  group: laplacian
  name: projects
  type: model
  version: "1.0.0"
  description: |
    The core modules for the Laplacian generator.
  module_repositories:
    local:
      path: ./subprojects/mvn-repo
      url: https://github.com/nabla-squared/mvn-repo
      branch: master
    remote:
    - https://github.com/nabla-squared/mvn-repo
  model_files:
  - dest/
