project:
  group: laplacian
  name: projects
  type: model
  version: "1.0.0"
  description: |
    The core modules for the Laplacian generator.
  module_repositories:
    local:
      path: ./subprojects/mvn-repo
      url: https://github.com/nabla-squared/mvn-repo
      branch: master
    remote:
    - https://github.com/nabla-squared/mvn-repo
  plugins:
  - group: laplacian
    name: project.schema-plugin
    version: '1.0.0'
  models:
  - group: laplacian
    name: projects
    version: '1.0.0'
  - group: laplacian
    name: project.document-content
    version: '1.0.0'
  templates:
  - group: laplacian
    name: project.base-template
    version: '1.0.0'

