project:
  group: laplacian
  name: projects
  version: "1.0.0"
  description: |
    The core modules for the Laplacian generator.
  module_repositories:
    local:
      path: ./subprojects/mvn-repo
      url: https://github.com/nabla-squared/mvn-repo
      branch: master
    remote:
    - https://github.com/nabla-squared/mvn-repo
  schemas:
  - group: laplacian
    name: schema.project
    version: '1.0.0'
  model_files:
  - model/project.yaml
  templates:
  - group: laplacian
    name: template.project.document
    version: '1.0.0'
