project:
  group: laplacian-arch
  name: schema.service-api
  type: schema
  namespace: laplacian.arch.service.api
  version: '1.0.0'
  description: |
    A schema for service-api architecture model.
  subprojects: []
  schemas:
  - group: laplacian
    name: schema.metamodel
    version: '1.0.0'
  - group: laplacian
    name: schema.project
    version: '1.0.0'
  - group: laplacian-arch
    name: schema.datasource
    version: '1.0.0'
  templates:
  - group: laplacian
    name: template.schema
    version: '1.0.0'
  models:
  - group: laplacian
    name: model.metamodel
    version: '1.0.0'
  - group: laplacian-arch
    name: model.datasource
    version: '1.0.0'
  - group: laplacian-arch
    name: model.service-api
    version: '1.0.0'
  model_files: []
  template_files: []
