project:
  group: laplacian
  name: metamodel-plugin
  type: plugin
  namespace: laplacian.metamodel
  version: '1.0.0'
  description: |
    A model which expresses the logical structure of laplacian-based projects and modules.
  subprojects: []
  schemas: []
  plugins:
  - group: laplacian
    name: metamodel-plugin
    version: '1.0.0'
  - group: laplacian
    name: project.schema-plugin
    version: '1.0.0'
  templates:
  - group: laplacian
    name: schema.plugin-template
    version: '1.0.0'
  models:
  - group: laplacian
    name: metamodel
    version: '1.0.0'
  model_files: []
  template_files: []
