project:
  group: laplacian
  name: metamodel-plugin
  type: schema-plugin
  namespace: laplacian.metamodel
  version: '1.0.0'
  description: |
    A model which expresses the logical structure of laplacian-based projects and modules.
  models:
  - group: laplacian
    name: metamodel
    version: '1.0.0'
