project:
  group: laplacian-arch
  name: datasource.schema-plugin
  type: schema-plugin
  namespace: laplacian.arch.datasource
  version: '1.0.0'
  description: |
    A schema gradle plugin for the datasource arch model
  models:
  - group: laplacian-arch
    name: datasource.schema-model
    version: '1.0.0'
