project:
  sources:
  - "README.md"
  - ".editorconfig"
  - ".gitattributes"
  - ".gitignore"
  - "model/project/sources.yaml"
  - "model/project.yaml"
  - "src/project/subprojects/laplacian-arch.datasource.flyway-migration-template.yaml"
  - "src/project/subprojects/laplacian-arch.datasource.schema-model.yaml"
  - "src/project/subprojects/laplacian-arch.datasource.schema-plugin.yaml"
  - "src/project/subprojects/laplacian-arch.model.service-api.yaml"
  - "src/project/subprojects/laplacian-arch.schema.service-api.yaml"
  - "src/project/subprojects/laplacian-arch.template.service-api.springboot2.yaml"
  - "src/project/subprojects/laplacian.metamodel-plugin.yaml"
  - "src/project/subprojects/laplacian.metamodel.yaml"
  - "src/project/subprojects/laplacian.project.base-template.yaml"
  - "src/project/subprojects/laplacian.project.document-content.yaml"
  - "src/project/subprojects/laplacian.project.project-types.yaml"
  - "src/project/subprojects/laplacian.project.schema-model.yaml"
  - "src/project/subprojects/laplacian.project.schema-plugin.yaml"
  - "src/project/subprojects/laplacian.schema.document-template.yaml"
  - "src/project/subprojects/laplacian.schema.plugin-template.yaml"
