project:
  group: laplacian
  name: project.schema-plugin
  type: schema-plugin
  namespace: laplacian.project
  version: '1.0.0'
  description: |
    A schema-plugin for project models.
  plugins:
  - group: laplacian
    name: common-model-plugin
    version: '1.0.0'
  models:
  - group: laplacian
    name: project.schema-model
    version: '1.0.0'
  - group: laplacian
    name: common-model
    version: '1.0.0'

