project:
  group: laplacian
  name: common-model-plugin
  type: schema-plugin
  namespace: laplacian.common
  version: '1.0.0'
  description: |
    Plugin module for the laplacian common model.
  models:
  - group: laplacian
    name: common-model
    version: '1.0.0'
