project:
  group: laplacian
  name: schema.metamodel
  type: schema
  namespace: laplacian.metamodel
  version: '1.0.0'
  description: |
    A model which expresses the logical structure of laplacian-based projects and modules.
  subprojects: []
  schemas:
  - group: laplacian
    name: schema.metamodel
    version: '1.0.0'
  templates:
  - group: laplacian
    name: template.schema
    version: '1.0.0'
  models:
  - group: laplacian
    name: model.metamodel
    version: '1.0.0'
  model_files: []
  template_files: []
