project:
  group: laplacian
  name: schema.metamodel
  type: schema
  namespace: laplacian.metamodel
  version: '1.0.0'
  subprojects: []
  schemas:
  - group: laplacian
    name: schema.metamodel
    version: '1.0.0'
  templates:
  - group: laplacian
    name: template.schema
    version: '1.0.0'
  models: []
  model_files:
  - /home/iwauo/workspace/laplacian.projects/./subprojects/laplacian.model.metamodel/model/entities
  template_files: []
