project:
  group: laplacian
  name: schema.project
  type: schema
  namespace: laplacian.project
  version: '1.0.0'
  subprojects: []
  schemas:
  - group: laplacian
    name: schema.metamodel
    version: '1.0.0'
  templates:
  - group: laplacian
    name: template.schema
    version: '1.0.0'
  models:
  - group: laplacian
    name: model.project
    version: '1.0.0'
  model_files: []
  template_files: []
